apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine:latest
      script: |
        #!/bin/sh
        echo "Cleaning up..."

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  steps:
    - name: nose
      image: python:3.11
      script: |
        #!/bin/sh
        pip install nose
        nosetests
